# Uncomment the next line to define a global platform for your project
  platform :ios, '15.6'

target 'Colorpicker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Colorpicker
  pod 'trackier-ios-sdk'

end
